'use client';

import { FormEvent, useEffect, useState } from 'react';
import { Loader2, Plus, ShieldCheck, X } from 'lucide-react';
import { createRole, listRoles } from '@/lib/api/queries';
import type { Role } from '@/lib/types';
import { PageHeading } from '@/components/ui/page-heading';
import { EmptyState, Panel } from '@/components/ui/panel';
import { StatusPill } from '@/components/ui/status-pill';

export default function RolesPage() { const [roles, setRoles] = useState<Role[]>([]); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { listRoles().then(setRoles).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, []); return <div><PageHeading eyebrow="Access / Policy" title="Roles & permissions" description="Define reusable access profiles that inherit permissions for every assigned user." action={{ label: 'Create role', onClick: () => setOpen(true) }} />{error && <p role="alert" className="mb-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<Panel><div className="border-b border-slate-100 px-6 py-5"><h3 className="font-semibold text-ink">Role catalog</h3><p className="mt-1 text-sm text-slate">Permission assignment remains governed by the service layer.</p></div>{loading ? <div className="flex justify-center p-14"><Loader2 className="h-6 w-6 animate-spin text-brand" /></div> : roles.length === 0 ? <EmptyState title="No roles yet" description="Create a reusable role profile for your procurement teams." /> : <div className="grid gap-4 p-6 md:grid-cols-2 xl:grid-cols-3">{roles.map((role) => <div key={role.id} className="rounded-2xl border border-slate-100 p-5 transition hover:border-brand/30 hover:shadow-sm"><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-brand-soft text-brand"><ShieldCheck className="h-5 w-5" /></div><StatusPill active={role.isActive} /></div><p className="mt-5 font-semibold text-ink">{role.name}</p><p className="mt-1 font-mono text-xs text-brand">{role.code}</p><p className="mt-4 text-sm leading-6 text-slate">{role.description || 'No description provided for this role.'}</p></div>)}</div>}</Panel>{open && <RoleForm onClose={() => setOpen(false)} onCreated={(role) => { setRoles((current) => [role, ...current]); setOpen(false); }} />}</div>; }
function RoleForm({ onClose, onCreated }: { onClose: () => void; onCreated: (role: Role) => void }) { const [form, setForm] = useState({ code: '', name: '', description: '' }); const [pending, setPending] = useState(false); const [error, setError] = useState(''); async function submit(event: FormEvent) { event.preventDefault(); setPending(true); try { onCreated(await createRole(form)); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create role'); } finally { setPending(false); } } return <div className="fixed inset-0 z-50 flex items-end justify-center bg-ink/30 p-4 sm:items-center"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand">Access configuration</p><h3 className="mt-2 text-xl font-semibold text-ink">Create role</h3></div><button onClick={onClose} aria-label="Close dialog" className="rounded-lg p-2 text-slate hover:bg-cloud"><X className="h-5 w-5" /></button></div><form onSubmit={submit} className="mt-7 space-y-5"><div><label htmlFor="role-code" className="text-sm font-semibold">Role code</label><input id="role-code" className="field font-mono" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} placeholder="PROCUREMENT_OFFICER" required /></div><div><label htmlFor="role-name" className="text-sm font-semibold">Role name</label><input id="role-name" className="field" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></div><div><label htmlFor="role-description" className="text-sm font-semibold">Description</label><textarea id="role-description" className="field min-h-24 resize-none" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div>{error && <p role="alert" className="text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="button-secondary">Cancel</button><button className="button-primary" disabled={pending}>{pending && <Loader2 className="h-4 w-4 animate-spin" />}<Plus className="h-4 w-4" />Create role</button></div></form></div></div>; }
