'use client';

import { FormEvent, useEffect, useState } from 'react';
import { Loader2, Plus, ShieldCheck, X } from 'lucide-react';
import { assignRolePermissions, createPermission, createRole, listPermissions, listRoles } from '@/lib/api/queries';
import type { Permission, Role } from '@/lib/types';
import { PageHeading } from '@/components/ui/page-heading';
import { EmptyState, Panel } from '@/components/ui/panel';
import { StatusPill } from '@/components/ui/status-pill';

export default function RolesPage() {
  const [roles, setRoles] = useState<Role[]>([]); const [permissions, setPermissions] = useState<Permission[]>([]); const [open, setOpen] = useState(false); const [permissionOpen, setPermissionOpen] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { Promise.all([listRoles(), listPermissions()]).then(([nextRoles, nextPermissions]) => { setRoles(nextRoles); setPermissions(nextPermissions); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, []);
  return <div><PageHeading eyebrow="Access / Policy" title="Roles & permissions" description="Define reusable access profiles that inherit permissions for every assigned user." action={{ label: 'Create role', onClick: () => setOpen(true) }} />{error && <p role="alert" className="mb-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<Panel><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h3 className="font-semibold text-ink">Role catalog</h3><p className="mt-1 text-sm text-slate">Permissions are assigned to roles and inherited by users through scoped assignments.</p></div></div>{loading ? <div className="flex justify-center p-14"><Loader2 className="h-6 w-6 animate-spin text-brand" /></div> : roles.length === 0 ? <EmptyState title="No roles yet" description="Create a reusable role profile for your procurement teams." /> : <div className="grid gap-4 p-6 md:grid-cols-2 xl:grid-cols-3">{roles.map((role) => <div key={role.id} className="rounded-2xl border border-slate-100 p-5 transition hover:border-brand/30 hover:shadow-sm"><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-brand-soft text-brand"><ShieldCheck className="h-5 w-5" /></div><StatusPill active={role.isActive} /></div><p className="mt-5 font-semibold text-ink">{role.name}</p><p className="mt-1 font-mono text-xs text-brand">{role.code}</p><p className="mt-4 text-sm leading-6 text-slate">{role.description || 'No description provided for this role.'}</p><p className="mt-4 text-xs font-semibold text-brand">{role.permissionIds?.length ?? 0} permissions inherited</p></div>)}</div>}</Panel><PermissionCatalog permissions={permissions} onCreate={async (permission) => { const created = await createPermission(permission); setPermissions((current) => [created, ...current]); }} onOpen={() => setPermissionOpen(true)} />{open && <RoleForm permissions={permissions} onClose={() => setOpen(false)} onCreated={(role) => { setRoles((current) => [role, ...current]); setOpen(false); }} />}{permissionOpen && <PermissionForm onClose={() => setPermissionOpen(false)} onCreated={async (permission) => { const created = await createPermission(permission); setPermissions((current) => [created, ...current]); setPermissionOpen(false); }} />}</div>;
}

function PermissionCatalog({ permissions, onOpen }: { permissions: Permission[]; onOpen: () => void; onCreate: (permission: { code: string; name: string; description?: string }) => Promise<void> }) {
  return <Panel className="mt-6"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h3 className="font-semibold text-ink">Permission catalog</h3><p className="mt-1 text-sm text-slate">Maintain the reusable server-side capabilities available to roles.</p></div><button className="button-secondary" onClick={onOpen}><Plus className="h-4 w-4" />Add permission</button></div>{permissions.length === 0 ? <EmptyState title="No permissions yet" description="Create the first capability for your access model." /> : <div className="divide-y divide-slate-100">{permissions.map((permission) => <div key={permission.id} className="flex items-center justify-between px-6 py-4"><div><p className="font-medium text-ink">{permission.name}</p><p className="font-mono text-xs text-brand">{permission.code}</p></div><p className="max-w-md text-right text-sm text-slate">{permission.description || 'No description provided.'}</p></div>)}</div>}</Panel>;
}

function PermissionForm({ onClose, onCreated }: { onClose: () => void; onCreated: (permission: { code: string; name: string; description?: string }) => Promise<void> }) {
  const [form, setForm] = useState({ code: '', name: '', description: '' }); const [pending, setPending] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); setPending(true); try { await onCreated(form); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create permission'); } finally { setPending(false); } }
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-ink/30 p-4 sm:items-center"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand">Access configuration</p><h3 className="mt-2 text-xl font-semibold text-ink">Add permission</h3></div><button onClick={onClose} aria-label="Close dialog" className="rounded-lg p-2 text-slate hover:bg-cloud"><X className="h-5 w-5" /></button></div><form onSubmit={submit} className="mt-7 space-y-5"><div><label htmlFor="permission-code" className="text-sm font-semibold">Permission code</label><input id="permission-code" className="field font-mono" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} placeholder="organization.manage" required /></div><div><label htmlFor="permission-name" className="text-sm font-semibold">Permission name</label><input id="permission-name" className="field" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></div><div><label htmlFor="permission-description" className="text-sm font-semibold">Description</label><textarea id="permission-description" className="field min-h-24 resize-none" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div>{error && <p role="alert" className="text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="button-secondary">Cancel</button><button className="button-primary" disabled={pending}>{pending && <Loader2 className="h-4 w-4 animate-spin" />}<Plus className="h-4 w-4" />Add permission</button></div></form></div></div>;
}

function RoleForm({ permissions, onClose, onCreated }: { permissions: Permission[]; onClose: () => void; onCreated: (role: Role) => void }) {
  const [form, setForm] = useState({ code: '', name: '', description: '' }); const [selected, setSelected] = useState<string[]>([]); const [pending, setPending] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); setPending(true); try { const role = await createRole(form); onCreated(await assignRolePermissions(role.id, selected)); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create role'); } finally { setPending(false); } }
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]);
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-ink/30 p-4 sm:items-center"><div className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand">Access configuration</p><h3 className="mt-2 text-xl font-semibold text-ink">Create role</h3></div><button onClick={onClose} aria-label="Close dialog" className="rounded-lg p-2 text-slate hover:bg-cloud"><X className="h-5 w-5" /></button></div><form onSubmit={submit} className="mt-7 space-y-5"><div><label htmlFor="role-code" className="text-sm font-semibold">Role code</label><input id="role-code" className="field font-mono" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} placeholder="PROCUREMENT_OFFICER" required /></div><div><label htmlFor="role-name" className="text-sm font-semibold">Role name</label><input id="role-name" className="field" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></div><div><label htmlFor="role-description" className="text-sm font-semibold">Description</label><textarea id="role-description" className="field min-h-24 resize-none" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div><fieldset><legend className="text-sm font-semibold">Permissions inherited by this role</legend><div className="mt-2 space-y-2 rounded-xl border border-slate-200 p-3">{permissions.length === 0 ? <p className="text-sm text-slate">No permissions configured.</p> : permissions.map((permission) => <label key={permission.id} className="flex cursor-pointer items-start gap-3 rounded-lg p-2 hover:bg-cloud"><input type="checkbox" checked={selected.includes(permission.id)} onChange={() => toggle(permission.id)} className="mt-0.5 h-4 w-4 rounded border-slate-300 text-brand focus:ring-brand" /><span><span className="block text-sm font-medium text-ink">{permission.name}</span><span className="font-mono text-xs text-slate">{permission.code}</span></span></label>)}</div></fieldset>{error && <p role="alert" className="text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="button-secondary">Cancel</button><button className="button-primary" disabled={pending}>{pending && <Loader2 className="h-4 w-4 animate-spin" />}<Plus className="h-4 w-4" />Create role</button></div></form></div></div>;
}
