'use client';

import { FormEvent, useEffect, useState } from 'react';
import { Check, Edit3, Loader2, MoreHorizontal, X } from 'lucide-react';
import { createOrganization, listOrganizations, setOrganizationStatus, updateOrganization } from '@/lib/api/queries';
import type { Organization } from '@/lib/types';
import { PageHeading } from '@/components/ui/page-heading';
import { EmptyState, Panel } from '@/components/ui/panel';
import { StatusPill } from '@/components/ui/status-pill';

export default function OrganizationsPage() { const [items, setItems] = useState<Organization[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [showForm, setShowForm] = useState(false); const [editing, setEditing] = useState<Organization | null>(null); const refresh = () => { setLoading(true); listOrganizations().then(setItems).catch((e) => setError(e.message)).finally(() => setLoading(false)); }; useEffect(refresh, []);
  async function save(body: { code: string; name: string }) { try { const saved = editing ? await updateOrganization(editing.id, body) : await createOrganization(body); setItems((current) => editing ? current.map((item) => item.id === saved.id ? saved : item) : [saved, ...current]); setShowForm(false); setEditing(null); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save organization'); } }
  async function toggle(item: Organization) { try { const saved = await setOrganizationStatus(item.id, !item.isActive); setItems((current) => current.map((currentItem) => currentItem.id === saved.id ? saved : currentItem)); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update status'); } }
  return <div><PageHeading eyebrow="Governance / Organization" title="Organizations" description="Manage the companies that make up the ABC Group procurement network." action={{ label: 'Add organization', onClick: () => { setEditing(null); setShowForm(true); } }} />{error && <div role="alert" className="mb-5 rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm text-red-700">{error}<button onClick={() => setError('')} className="float-right" aria-label="Dismiss error"><X className="h-4 w-4" /></button></div>}<Panel><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h3 className="font-semibold text-ink">Organization directory</h3><p className="mt-1 text-sm text-slate">{items.length} configured records</p></div><span className="rounded-full bg-brand-soft px-3 py-1 text-xs font-semibold text-brand">Group master</span></div>{loading ? <div className="flex justify-center p-14"><Loader2 className="h-6 w-6 animate-spin text-brand" /></div> : items.length === 0 ? <EmptyState title="No organizations yet" description="Create the first company record to begin configuring the group." /> : <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-cloud text-xs uppercase tracking-wider text-slate"><tr><th className="px-6 py-3 font-semibold">Code</th><th className="px-6 py-3 font-semibold">Organization</th><th className="px-6 py-3 font-semibold">Status</th><th className="px-6 py-3 text-right font-semibold">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => <tr key={item.id} className="transition hover:bg-cloud/70"><td className="px-6 py-4 font-mono text-xs font-semibold text-brand">{item.code}</td><td className="px-6 py-4 font-semibold text-ink">{item.name}</td><td className="px-6 py-4"><StatusPill active={item.isActive} /></td><td className="px-6 py-4"><div className="flex justify-end gap-2"><button className="button-secondary px-3 py-2" onClick={() => { setEditing(item); setShowForm(true); }} aria-label={`Edit ${item.name}`}><Edit3 className="h-4 w-4" />Edit</button><button className={item.isActive ? 'button-danger' : 'button-secondary px-3 py-2'} onClick={() => void toggle(item)}>{item.isActive ? <X className="h-4 w-4" /> : <Check className="h-4 w-4" />}{item.isActive ? 'Deactivate' : 'Activate'}</button><button className="rounded-xl border border-slate-200 p-2 text-slate" aria-label={`More actions for ${item.name}`}><MoreHorizontal className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div>}</Panel>{showForm && <OrganizationForm initial={editing} onClose={() => { setShowForm(false); setEditing(null); }} onSave={save} />}</div>; }

function OrganizationForm({ initial, onClose, onSave }: { initial: Organization | null; onClose: () => void; onSave: (body: { code: string; name: string }) => Promise<void> }) { const [code, setCode] = useState(initial?.code ?? ''); const [name, setName] = useState(initial?.name ?? ''); const [pending, setPending] = useState(false); const [error, setError] = useState(''); async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setError(''); try { await onSave({ code, name }); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save'); } finally { setPending(false); } } return <div className="fixed inset-0 z-50 flex items-end justify-center bg-ink/30 p-4 sm:items-center"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand">Organization master</p><h3 className="mt-2 text-xl font-semibold text-ink">{initial ? 'Update organization' : 'Add organization'}</h3></div><button onClick={onClose} className="rounded-lg p-2 text-slate hover:bg-cloud" aria-label="Close dialog"><X className="h-5 w-5" /></button></div><form onSubmit={submit} className="mt-7 space-y-5"><div><label htmlFor="organization-code" className="text-sm font-semibold">Organization code</label><input id="organization-code" value={code} onChange={(e) => setCode(e.target.value)} className="field font-mono" placeholder="ABC-UNIT-01" required /></div><div><label htmlFor="organization-name" className="text-sm font-semibold">Organization name</label><input id="organization-name" value={name} onChange={(e) => setName(e.target.value)} className="field" placeholder="ABC Manufacturing Limited" required /></div>{error && <p role="alert" className="text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-3 pt-2"><button type="button" onClick={onClose} className="button-secondary">Cancel</button><button className="button-primary" disabled={pending}>{pending && <Loader2 className="h-4 w-4 animate-spin" />}{initial ? 'Save changes' : 'Create organization'}</button></div></form></div></div>; }
